server:
  port: 8001

authentication-service:
  url: http://localhost:8002
review-service:
  url: http://localhost:8001
property-service:
  url: http://localhost:8000
image-processing-service:
  url: http://localhost:8003

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: arc
    password: arc

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
